#!/usr/bin/env bash

if [ -z $1 ]; then
  kubectl get pods
else
  pod=$(kubectl get pods | grep $1 | head -1 | awk '{ print $1 }')

  echo -e "\e[32m** running: kubectl exec -ti $pod -- /bin/bash **\e[0m" >&2

  kubectl exec -ti $pod -- /bin/bash
fi
